id: I1A629EA4
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:35:15.196508'
last_modified: '2022-06-18T20:35:15.196526'
parser: null
source_metadata:
  title: Hagiography of Glang thang spyan snga Kun dga rdo rje (1424–1477/78?)
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
  description: 'Digital version 4.0 {Tibetan}; master xml (completed: 2012-09); head
    entries supplemented and linebreaks encoded, revision in process, no thematic
    TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/362
  bases:
    494d:
      title: Hagiography of Glang thang spyan snga Kun dga rdo rje (1424–1477/78?)
      order: 1
      base_file: 494d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
